version: "3.8"
services:
  # Application
  app:
    build:
      context: ./docker/services/app
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      net:
  # Web Server
  web:
    build:
      context: ./docker/services/web
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./docker/services/web/conf.d/:/etc/nginx/conf.d/
      - ./docker/services/web/ssl/:/etc/nginx/ssl/
      - ./docker/services/web/log/:/var/log/nginx/
    networks:
      expose_network:
      net:
    depends_on:
      - app
    environment:
      - VIRTUAL_HOST=your_domain_name.local
  # Database
  database:
    platform: linux/x86_64
    image: mysql:8.0.25
    restart: unless-stopped
    volumes:
      - ./docker/volumes/mysql:/var/lib/mysql
    networks:
      net:
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      TZ: UTC
    ports:
      - "3306"
    command:
      - --sort_buffer_size=402653184
      - --default-time-zone=+00:00
  # Caching
  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - ./docker/volumes/redis:/data
      - ./docker/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      net:
    command: /bin/sh -c "redis-server --requirepass ${REDIS_PASSWORD}"
    ports:
      - "6379"
networks:
    # Join proxy network for exposing http services
    expose_network:
        external:
            name: web_proxy
    # Internal network for this project
    net: